image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

build_image:
  stage: build
  script: ci/build-image.sh

build:
  stage: test
  image: $IMAGE_TAG
  script: nix-build
